name: Teste Secret

on:
  push:

jobs:

  teste:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Mostrar mensagem
        run: echo "Workflow funcionando"

      - name: Verificar secret
        run: echo "Secret disponível"

        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}